import logging
from logging.handlers import RotatingFileHandler
from pathlib import Path

import structlog

from src.config import get_settings


def setup_logging() -> None:
    """
    Configure structlog processors to capture both app and system logs as JSON.
    """
    settings = get_settings()
    log_dir = "logs"
    log_level = getattr(logging, settings.log_level.upper())

    Path(log_dir).mkdir(exist_ok=True)

    # 1. Define processors shared by both structlog and standard logging
    shared_processors = [
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.add_log_level,
        structlog.stdlib.add_logger_name,
        structlog.processors.TimeStamper(fmt="%Y-%m-%d %H:%M.%S"),
        structlog.processors.EventRenamer("message"),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.ExceptionRenderer(),
    ]

    # 2. Configure structlog to prepare events for the stdlib formatter
    structlog.configure(
        processors=shared_processors
        + [
            structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
        ],
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
        cache_logger_on_first_use=True,
    )

    # 3. Create the formatter that bridges standard logging to structlog's JSON renderer
    formatter = structlog.stdlib.ProcessorFormatter(
        # foreign_pre_chain applies our shared processors to logs NOT generated by structlog (e.g. httpcore)
        foreign_pre_chain=shared_processors,
        processors=[
            structlog.stdlib.ProcessorFormatter.remove_processors_meta,
            structlog.processors.JSONRenderer(),
        ],
    )

    # 4. Set up the file handler and attach the structlog formatter
    file_handler = RotatingFileHandler(
        filename=f"{log_dir}/app.log",
        maxBytes=10 * 1024 * 1024,  # 10MB per file
        backupCount=5,  # Keep 5 backup files
        encoding="utf-8",
    )
    file_handler.setFormatter(formatter)

    # 5. Configure the root python logger to route everything through our handler
    root_logger = logging.getLogger()
    root_logger.setLevel(log_level)

    # Clear existing handlers to prevent duplicate raw string logs
    root_logger.handlers.clear()
    root_logger.addHandler(file_handler)
